### ISSUE TITLE
Update {datasets} vectors

### ISSUE THREAD

**Issue by k5cents** [kiernann/usa#2]
The following vectors are part of the original `datasets` package: 

- [x] `state.abb`
- [x] `state.area`
- [x] `state.center`
- [x] `state.division`
- [x] `state.name`
- [x] `state.region`

They all need to be updated and overwritten.

**Comment by kiernann** [comment]
Find a better source for literacy rates? The only data I can find is from 2003 and only covers the 50 states (and DC). I might have to scrape together stats from many different sources manually.

**Comment by kiernann** [comment]
Might be worth using a mean number ["cooling days"](https://www.weather.gov/key/climate_heat_cool) instead of "days below freezing." 

> Degree days are based on the assumption that when the outside temperature is 65°F, we don't need heating or cooling to be comfortable. Degree days are the difference between the daily temperature mean, (high temperature plus low temperature divided by two) and 65°F. If the temperature mean is above 65°F, we subtract 65 from the mean and the result is **Cooling Degree Days**.

I can calculate that based on all the stations in a state across the last 30 years.
